### ISSUE TITLE
[Bug] the end to end examples in readme are missing 

### ISSUE THREAD

**Issue by biohaosen** [pinecone-io/pinecone-text#45]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In the places such as this:
For an end-to-end example, you can refer to our Quora dataset generation with SPLADE [notebook](https://github.com/pinecone-io/examples/blob/master/pinecone/sparse/splade/splade-vector-generation.ipynb).

and this:
For an end-to-end example, you can refer to our Quora dataset generation with BM25 [notebook](https://github.com/pinecone-io/examples/blob/master/pinecone/sparse/bm25/bm25-vector-generation.ipynb).

The notebook it is pointing to is invalid

### Expected Behavior

It should point to a valid example of end to end implementation of the sparse vector search. 

### Steps To Reproduce

1. Click into the link in readme.md
2. The link says 
```
The master branch of examples does not contain the path pinecone/sparse/bm25/bm25-vector-generation.ipynb.```

### Relevant log output

_No response_

### Environment

```markdown
- **OS**:
- **Language version**:
- **Pinecone client version**:
```

### Additional Context

I am curious as to why this happens.

**Comment by acatav** [comment]
Resolved, thanks for pointing it out
