### ISSUE TITLE
[Bug] Hybrid scaling func in readme is misleading

### ISSUE THREAD

**Issue by jamescalam** [pinecone-io/pinecone-text#53]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In readme you have:

`This method receives both a dense vector and a sparse vector, along with a convex scaling parameter alpha. It returns a tuple consisting of the scaled dense and sparse vectors according to the following formula: alpha * dense_vector + (1 - alpha) * sparse_vector.`

The formula shows you summing the two vectors, but I think it should return a tuple?

### Expected Behavior

Switch to:

This method receives both a dense vector and a sparse vector, along with a convex scaling parameter `alpha`. It returns a tuple consisting of the scaled dense and sparse vectors according to the following formula: `(alpha * dense_vector, (1 - alpha) * sparse_vector)`.

### Steps To Reproduce

N/A

### Environment

```markdown
- **OS**:
- **Language version**:
- **Pinecone client version**:
```

**Comment by acatav** [comment]
thanks for solving the issue in #54, I just merged it
